spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base-component-organization?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: admin@dev
    hikari:
      pool-name: HikariPool-1
      minimum-idle: 10 #池中维护的最小空闲连接数，默认10
      maximum-pool-size: 20 #池中最大连接数，包括闲置和使用中的连接，默认10
      connection-timeout: 30000 #等待来自池的连接的最大毫秒数，默认30秒(如果小于250毫秒，则被重置回30秒)
      max-lifetime: 1800000 #池中连接最长生命周期，值0表示无限生命周期，默认1800000即30分钟(如果不等于0且小于30秒则会被重置回30分钟)
      idle-timeout: 600000 #连接允许在池中闲置的最长时间，默认600000（10分钟），如果idleTimeout+1秒>maxLifetime 且 maxLifetime>0，则会被重置为0（代表永远不会退出）；如果idleTimeout!=0且小于10秒，则会被重置为10秒
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认：true
      validation-timeout: 5000 #连接将被测试活动的最大时间量，如果小于250毫秒，则会被重置回5秒,默认5000
  redis:
    host: 172.31.119.38
    password: admin@dev
    port: 6379
logging:
  level:
    com: DEBUG
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.talelife.base.component.organization.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
idGenerator:
  type: timeid #使用算法uuid,snowflake
  #type设置为snowflake才需要配置
  zookeeper:
    server-lists: 172.31.118.250:2181 #多个地址用逗号分隔
    group: component-org #分组名称